<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ForgotUrl_Mailinator</name>
   <tag></tag>
   <elementGuidId>7d3a7f1e-b225-4996-8e6b-32dd3556f204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(@href,'https://hcc2-fe-qc.hancocks.co.uk/customer/account/createpassword')])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
