<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_OnlineDeliveryItems</name>
   <tag></tag>
   <elementGuidId>d93f2b40-d673-41b8-8a2b-8cca8df44507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h3[@class='mb-0'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
